/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as ItensPorBoxRouteImport } from './routes/itens-por-box'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as GestorRouteImport } from './routes/gestor'
import { Route as ColetaRouteImport } from './routes/coleta'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'

const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const ItensPorBoxRoute = ItensPorBoxRouteImport.update({
  id: '/itens-por-box',
  path: '/itens-por-box',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const GestorRoute = GestorRouteImport.update({
  id: '/gestor',
  path: '/gestor',
  getParentRoute: () => rootRouteImport,
} as any)
const ColetaRoute = ColetaRouteImport.update({
  id: '/coleta',
  path: '/coleta',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/coleta': typeof ColetaRoute
  '/gestor': typeof GestorRoute
  '/historico': typeof HistoricoRoute
  '/itens-por-box': typeof ItensPorBoxRoute
  '/ranking': typeof RankingRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/coleta': typeof ColetaRoute
  '/gestor': typeof GestorRoute
  '/historico': typeof HistoricoRoute
  '/itens-por-box': typeof ItensPorBoxRoute
  '/ranking': typeof RankingRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/coleta': typeof ColetaRoute
  '/gestor': typeof GestorRoute
  '/historico': typeof HistoricoRoute
  '/itens-por-box': typeof ItensPorBoxRoute
  '/ranking': typeof RankingRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/coleta'
    | '/gestor'
    | '/historico'
    | '/itens-por-box'
    | '/ranking'
    | '/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/coleta'
    | '/gestor'
    | '/historico'
    | '/itens-por-box'
    | '/ranking'
    | '/usuarios'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/coleta'
    | '/gestor'
    | '/historico'
    | '/itens-por-box'
    | '/ranking'
    | '/usuarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ColetaRoute: typeof ColetaRoute
  GestorRoute: typeof GestorRoute
  HistoricoRoute: typeof HistoricoRoute
  ItensPorBoxRoute: typeof ItensPorBoxRoute
  RankingRoute: typeof RankingRoute
  UsuariosRoute: typeof UsuariosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/itens-por-box': {
      id: '/itens-por-box'
      path: '/itens-por-box'
      fullPath: '/itens-por-box'
      preLoaderRoute: typeof ItensPorBoxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestor': {
      id: '/gestor'
      path: '/gestor'
      fullPath: '/gestor'
      preLoaderRoute: typeof GestorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coleta': {
      id: '/coleta'
      path: '/coleta'
      fullPath: '/coleta'
      preLoaderRoute: typeof ColetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ColetaRoute: ColetaRoute,
  GestorRoute: GestorRoute,
  HistoricoRoute: HistoricoRoute,
  ItensPorBoxRoute: ItensPorBoxRoute,
  RankingRoute: RankingRoute,
  UsuariosRoute: UsuariosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
